GET http://localhost:5000/produtos/ HTTP/1.1

###

GET http://localhost:5000/produtos/?raca=cao HTTP/1.1

###

GET http://localhost:5000/produtos/1/ HTTP/1.1

###

DELETE http://localhost:5000/produtos/2/ HTTP/1.1

###

GET https://source.unsplash.com/1600x900/?nature,water HTTP/1.1

###

GET https://source.unsplash.com/random HTTP/1.1

###

POST http://localhost:5000/produtos/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "raca": "peixe",
  "valor": "70.00",
  "quantidade": 5
}

###

PUT http://localhost:5000/produtos/1/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "raca": "ave",
  "valor": "70.00",
  "quantidade": 5
}

###

POST http://localhost:5000/clientes/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "firstName": "William",
  "lastName": "Lagos"
}

###

POST http://localhost:5000/compras/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "product": { "id": 1 },
  "customer": { "id": 1 }
}

###

PUT http://localhost:5000/compras/1/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "product": { "id": 1 },
  "customer": { "id": 2 }
}

###

GET http://localhost:5000/compras/ HTTP/1.1

###

GET http://localhost:5000/compras/1/ HTTP/1.1

###

DELETE http://localhost:5000/compras/1/ HTTP/1.1

###

POST http://localhost:5000/compras/finalizar HTTP/1.1
